# In order to support static IP for survey-serve container, we need to use version 2. Version 3
# doesn't recognize the network `gateway` field, but without a gateway defined the static IP
# assignment doesn't take effect.
# See:
#  - https://runnable.com/docker/docker-compose-networking
#  - https://github.com/docker/docker.github.io/pull/1636#issuecomment-304735171
version: "2"

services:

  aol:
    build: challenges/aol
    image: aol
    ports:
      - 5000:80

  crypto-2:
    build: challenges/crypto-2
    image: crypto-2
    ports:
      - 5001:5000

  exposed-server:
    build: challenges/exposed_server
    image: exposed-server
    ports:
      - 5002:80

  exposed-server-mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: s83PUk9nrd4
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: s83PUk9nrd4

  jollyroger:
    build: challenges/jollyroger
    image: jollyroger
    privileged: true
    ports:
      - 5003:5000

  lsb-stego:
    build: challenges/lsb_stego
    image: lsb-stego
    ports:
      - 5004:80

  math-machine2:
    build: challenges/math_machine2
    image: math-machine2
    ports:
      - 5005:5000

  math-machine3:
    build: challenges/math_machine3
    image: math-machine3
    ports:
      - 5006:5100

  obscure-security:
    build: challenges/obscure_security
    image: obscure-security
    ports:
      - 5007:80

  prize:
    build: challenges/prize
    image: prize
    ports:
      - 5008:80

  survey-serve:
    build: challenges/survey1/serve
    image: survey-serve
    networks:
      survey_net:
        ipv4_address: 10.0.0.189


  ssh-host:
    build: challenges/ssh_host
    image: ssh-host
    ports:
      - "2222:22"
    links:
      - feeling-lucky
      - man1
      - man2
      - survey-implant
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    #deploy:
    #  replicas: 3


  # The following services are for interactive challenges. Competitors will
  # pivot through the ssh-host to login to these containers.

  feeling-lucky:
    build: challenges/feeling_lucky
    image: feeling-lucky
    command: /bin/true

  man1:
    build: challenges/man1
    image: man1
    command: /bin/true

  man2:
    build: challenges/man2
    image: man2
    command: /bin/true

  survey-implant:
    build: challenges/survey1/implant
    image: survey-implant
    command: /bin/true


volumes:
  db_data:


networks:
  survey_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
