#!/bin/bash

#Get the API Key
read -p "Enter your api key:  " API_KEY
API_KEY="AKIAJMENS657XSBERGLA"
export AWS_ACCESS_KEY_ID=$API_KEY

#Get the API Secret Key
read -p "Enter your secret key:  " SECRET_KEY
SECRET_KEY="GapKDQXjjh9b1k4luRJU9SWL+fD2m6qcFKkIp1JG"
export AWS_SECRET_ACCESS_KEY=$SECRET_KEY

#Select Region
printf "What region would you like this instance to run in?\n"
printf "1.  Virgina\n"
printf "2.  Ohio\n"
printf "3.  Oregon\n"
printf "4.  Califonia\n"
printf "5.  London\n"
read -p "Selection:  " REGION

#Validate Region
if [ $REGION -eq 1 ]; then
	AWS_REGION="us-east-1"
elif [ $REGION -eq 2 ]; then
	AWS_REGION="us-east-2"
elif [ $REGION -eq 3 ]; then
	AWS_REGION="us-west-2"
elif [ $REGION -eq 4 ]; then
	AWS_REGION="us-west-1"
elif [ $REGION -eq 5 ]; then
	AWS_REGION="eu-west-1"
else
	echo "Invalid Selection"
	exit 1
fi

#Select Instance Size
printf "What size instance would you like to run?\n"
printf "1.  t2.micro (1 vCPU 1GB)\n"
printf "2.  t2.small (1 vCPU 2GB)\n"
printf "3.  t2.medium (2 vCPU 4GB)\n"
printf "4.  t2.large (2 vCPU 8GB)\n"
printf "5.  t2.xlarge (4 vCPU 16GB)\n"
printf "6.  t2.2xlarge (8 vCPU 32GB)\n"
read -p "Selection:  " INSTANCE_TYPE

#Validate Instance Size
if [ $INSTANCE_TYPE -eq 1 ]; then
	AWS_INSTANCE_TYPE="t2.micro"
elif [ $INSTANCE_TYPE -eq 2 ]; then
	AWS_INSTANCE_TYPE="t2.small"
elif [ $INSTANCE_TYPE -eq 3 ]; then
	AWS_INSTANCE_TYPE="t2.medium"
elif [ $INSTANCE_TYPE -eq 4 ]; then
	AWS_INSTANCE_TYPE="t2.large"
elif [ $INSTANCE_TYPE -eq 5 ]; then
	AWS_INSTANCE_TYPE="t2.xlarge"
elif [ $INSTANCE_TYPE -eq 6 ]; then
	AWS_INSTANCE_TYPE="t2.2xlarge"
else
	echo "Invalid Selection"
	exit 1
fi

#Set Key Policy Name
read -p "Enter the name of your key pair:  " KEY_PAIR
KEY_PAIR="anisible_test"

export ANSIBLE_HOST_KEY_CHECKING=False

ANSIBLE_ENABLE_TASK_DEBUGGER=True ansible-playbook -i ./hosts --extra-vars "instance_type=$AWS_INSTANCE_TYPE keypair=$KEY_PAIR region=$AWS_REGION" aws_build.yml

read -p "continue" STUFF

ANSIBLE_ENABLE_TASK_DEBUGGER=True ansible-playbook -i ./hosts server_build.yml

echo "Install Complete\n"

